version: '3.8'

services:
  testing-agent:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    image: testing-agent:latest
    container_name: testing-agent-prod
    restart: always
    environment:
      # OpenAI Configuration
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Slack Configuration
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_SIGNING_SECRET=${SLACK_SIGNING_SECRET}
      
      # Atlassian Configuration
      - JIRA_URL=${JIRA_URL}
      - CONFLUENCE_URL=${CONFLUENCE_URL}
      - ATLASSIAN_EMAIL=${ATLASSIAN_EMAIL}
      - ATLASSIAN_API_TOKEN=${ATLASSIAN_API_TOKEN}
      
      # Production Configuration
      - DEBUG=false
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    
    volumes:
      # Persistent storage for test outputs
      - testing-agent-videos:/home/app/videos
      - testing-agent-screenshots:/home/app/screenshots
      - testing-agent-reports:/home/app/reports
      - testing-agent-logs:/home/app/logs
    
    # Production resource limits
    deploy:
      resources:
        limits:
          memory: 4G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    
    # Network configuration
    networks:
      - testing-agent-network
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Read-only root filesystem (except for volumes)
    read_only: true
    tmpfs:
      - /tmp:noexec,nosuid,size=100m
      - /var/tmp:noexec,nosuid,size=50m
    
    # Logging configuration for production
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
        compress: "true"
    
    # Labels for monitoring
    labels:
      - "com.example.service=testing-agent"
      - "com.example.environment=production"
      - "com.example.version=1.0.0"

networks:
  testing-agent-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  testing-agent-videos:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/videos
  testing-agent-screenshots:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/screenshots
  testing-agent-reports:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/reports
  testing-agent-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/data/logs 